name: Android CI

on:
  push:
    branches:
    - master
    - staging
    - dev
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Write permission for Gradlew
      run: chmod +x ./gradlew
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Android Application 
      run: ./gradlew buildDevDebug
